version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stderr
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/taiga_mcp.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/taiga_mcp_errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  # Root logger
  root:
    level: INFO
    handlers: [console, file, error_file]
  
  # MCP server logger
  mcp_taiga_bridge:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  # Taiga client logger
  pytaigaclient:
    level: INFO
    handlers: [file]
    propagate: false
  
  # HTTP request logger
  httpx:
    level: WARNING
    handlers: [file]
    propagate: false
  
  # Uvicorn logger (for SSE transport)
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: false

# Development settings (override in production)
# Set environment variable: TAIGA_MCP_LOG_LEVEL=DEBUG for development
# Set environment variable: TAIGA_MCP_LOG_LEVEL=INFO for production
